<?php require_once 'engine/init.php'; include 'layout/overall/header.php'; ?>
<img src="layout/images/titles/t_servinfo.png"/><p>

Here you will find all basic information about <?php echo '<b>'.$config['site_title'].'</b>'; ?>
<br><br>
edit at .../www/serverinfo.php

<a href="sub.php?page=mechanics">Mechanics</a>...
<a href="powergamers.php">Powergamers</a>...
<a href="credits.php">Znote Credits</a>...
<a href="killers.php">Killers</a>...
<a href="deaths.php">Deaths</a>...
<b href="">Contact</b>...
<b href="">Credits</b>...
<b href="">Documentation</b>...
<b href="">Statistics</b>...

<?php include 'layout/overall/footer.php'; ?>